### ISSUE TITLE
Attribute "dividerSize" has already been defined

### ISSUE THREAD

**Issue by meeftah** [blazsolar/WeekDatePicker#1]
I'm using your horizontalpicker together with weekdatepicker and this error shows up
Error:(218) Attribute "dividerSize" has already been defined

**Comment by meeftah** [comment]
any update,..

**Comment by blazsolar** [comment]
I'll add prefix to attributes and I'll try to doit by the end of weekend.

**Comment by meeftah** [comment]
so? I need this for my project

**Comment by blazsolar** [comment]
Version `1.1` is available that prefixes all attributes with `wdp_`. This should fix your problem.
