### ISSUE TITLE
java.util.zip.ZipException: duplicate entry

### ISSUE THREAD

**Issue by mduisenov** [blazsolar/WeekDatePicker#13]
Cannot integrate into project

Error:Execution failed for task ':app:transformClassesWithJarMergingForInternalDebug'.

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/threeten/bp/chrono/AbstractChronology.class

I'm using "com.jakewharton.threetenabp:threetenabp:1.0.2"

**Comment by blazsolar** [comment]
The library is using `'org.threeten:threetenbp:1.3.1'` and it seams they are in conflict. 

Could you try adding library like so:

``` groovy
compile("solar.blaz:week-date-picker:1.2") {
    exclude group: 'org.threeten', module: 'threetenbp'
}
```

**Comment by mduisenov** [comment]
thanks, bro. I copied WeekDatePicker class into my custom view package. excluding is also fixing the problem too.
