### ISSUE TITLE
Add dot markers for day

### ISSUE THREAD

**Issue by antoxa2584x** [blazsolar/WeekDatePicker#7]
Please, add ability to add events to date
Small dots like this
![unnamed](https://cloud.githubusercontent.com/assets/8998205/15274987/9fa7927e-1ac8-11e6-9d95-ed29bf16cd3b.png)

**Comment by blazsolar** [comment]
Hi, 

you can already do this for separate day by using `WeekDayPicker.setDateIndicator(LocalDate date, boolean enabled)` method. 

You can si an example in libraries example project.
