### ISSUE TITLE
issues android kitkat and jellybean

### ISSUE THREAD

**Issue by elhak** [blazsolar/WeekDatePicker#9]
I have error in week picker at android < lolipop how to solve that?

**Comment by blazsolar** [comment]
can you give me some more informations

**Comment by elhak** [comment]
`Exception Details org.threeten.bp.zone.ZoneRulesException: No time-zone data files registered`

i got exception like that

**Comment by elhak** [comment]
and was i run that apps error like this
`android.view.InflateException: Binary XML file line #11: Error inflating class solar.blaz.date.week.WeekDatePicker`

**Comment by elhak** [comment]
ohh sorry is my fault.. ty case closed

**Comment by AjayVyas** [comment]
Hello elhak can  you help me to solve it. I am  getting the Same error.

**Comment by danieltigse** [comment]
Same error, how do you solve it?
